#!/usr/bin/env python3
"""Build the single-file prompt and a clean, shareable repository archive."""
from pathlib import Path
import re
import zipfile

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    'skills/daily-learning/SKILL.md',
    'skills/daily-learning/references/supadata.md',
    'skills/daily-learning/references/lesson-workflow.md',
    'skills/daily-learning/references/scheduling.md',
    'skills/daily-learning/assets/learner-profile.md',
    'skills/daily-learning/assets/learning-log.md',
    'skills/daily-learning/assets/lesson.md',
]
LINK = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')


def render_bundle():
    anchors = {str((ROOT / p).resolve()): f'section-{i + 1}'
               for i, p in enumerate(SOURCES)}
    parts = [
        '# Daily Learning — complete portable prompt\n\n'
        '<!-- Generated by scripts/build_bundle.py; edit the source skill files. -->\n\n'
        'Apply this workflow when I ask to set up or continue Daily Learning. '
        'If no subject has been supplied, start with the short intake. '
        'This file contains every required instruction and template; internal links '
        'point to sections below. A preview does not create a schedule. '
        'Use the tools actually available, and follow my explicit instructions '
        'and your platform rules.\n'
    ]
    for i, name in enumerate(SOURCES):
        source = ROOT / name
        body = source.read_text(encoding='utf-8')
        if body.startswith('---\n'):
            body = body.split('---\n', 2)[2].lstrip()

        def rewrite(match):
            label, target = match.groups()
            if target.startswith(('https://', 'http://', '#', 'mailto:')):
                return match.group(0)
            path = str((source.parent / target.split('#')[0]).resolve())
            if path not in anchors:
                raise ValueError(f'Unbundled reference in {name}: {target}')
            return f'[{label}](#{anchors[path]})'

        body = LINK.sub(rewrite, body)
        parts.append(f'\n---\n\n<a id="section-{i + 1}"></a>\n\n{body.rstrip()}\n')
    return ''.join(parts)


def archive_members():
    # Explicit public content only; never scoop up a user's working directory.
    top = ['README.md', 'START_HERE.md', 'DAILY_LEARNING.md', 'LICENSE', '.gitignore']
    files = [ROOT / p for p in top]
    for folder, suffixes in [('skills', {'.md'}), ('scripts', {'.py'}),
                             ('tests', {'.md'}), ('examples', {'.md', '.pdf'})]:
        files.extend(p for p in (ROOT / folder).rglob('*')
                     if p.is_file() and not p.is_symlink() and p.suffix in suffixes)
    return sorted(set(files))


def main():
    (ROOT / 'DAILY_LEARNING.md').write_text(render_bundle(), encoding='utf-8')
    output = ROOT / 'dist'
    output.mkdir(exist_ok=True)
    archive = output / 'daily-learning.zip'
    files = archive_members()
    with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_DEFLATED) as z:
        for path in files:
            info = zipfile.ZipInfo('daily-learning/' + path.relative_to(ROOT).as_posix(),
                                   date_time=(2026, 10, 2, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, path.read_bytes())
    print(f'Built DAILY_LEARNING.md and dist/daily-learning.zip ({len(files)} files).')


if __name__ == '__main__':
    main()
